// Code generated by go-varlink/varlinkgen. DO NOT EDIT.

package profileapi

import (
	"encoding/json"
	govarlink "github.com/emersion/go-varlink"
)

type Metadata struct {
	CorrelationId *string `json:"correlation_id,omitempty"`
	Locale        *string `json:"locale,omitempty"`
	UserAgent     *string `json:"user_agent,omitempty"`
}

type ProfileNotSupportedError struct{}

func (err *ProfileNotSupportedError) Error() string {
	return "varlink call failed: com.redhat.rhsm.testing.content.profile.ProfileNotSupported"
}

type SystemNotRegisteredError struct{}

func (err *SystemNotRegisteredError) Error() string {
	return "varlink call failed: com.redhat.rhsm.testing.content.profile.SystemNotRegistered"
}

type SendIn struct {
	Metadata *Metadata `json:"metadata,omitempty"`
}
type SendOut struct {
	Success bool `json:"success"`
}

type Client struct {
	*govarlink.Client
}

func unmarshalError(err error) error {
	verr, ok := err.(*govarlink.ClientError)
	if !ok {
		return err
	}
	var v error
	switch verr.Name {
	case "com.redhat.rhsm.testing.content.profile.ProfileNotSupported":
		v = new(ProfileNotSupportedError)
	case "com.redhat.rhsm.testing.content.profile.SystemNotRegistered":
		v = new(SystemNotRegisteredError)
	default:
		return err
	}
	if err := json.Unmarshal(verr.Parameters, v); err != nil {
		return err
	}
	return v
}
func (c Client) Send(in *SendIn) (*SendOut, error) {
	if in == nil {
		in = new(SendIn)
	}
	out := new(SendOut)
	err := c.Client.Do("com.redhat.rhsm.testing.content.profile.Send", in, out)
	return out, unmarshalError(err)
}

type Backend interface {
	Send(*SendIn) (*SendOut, error)
}

type Handler struct {
	Backend Backend
}

func marshalError(err error) error {
	var name string
	switch err.(type) {
	case *ProfileNotSupportedError:
		name = "com.redhat.rhsm.testing.content.profile.ProfileNotSupported"
	case *SystemNotRegisteredError:
		name = "com.redhat.rhsm.testing.content.profile.SystemNotRegistered"
	default:
		return err
	}
	return &govarlink.ServerError{
		Name:       name,
		Parameters: err,
	}
}
func (h Handler) HandleVarlink(call *govarlink.ServerCall, req *govarlink.ServerRequest) error {
	var (
		out interface{}
		err error
	)
	switch req.Method {
	case "com.redhat.rhsm.testing.content.profile.Send":
		in := new(SendIn)
		if err := json.Unmarshal(req.Parameters, in); err != nil {
			return err
		}
		out, err = h.Backend.Send(in)
	default:
		err = &govarlink.ServerError{
			Name:       "org.varlink.service.MethodNotFound",
			Parameters: map[string]string{"method": req.Method},
		}
	}
	if err != nil {
		return marshalError(err)
	}
	return call.CloseWithReply(out)
}

func (h Handler) Register(reg *govarlink.Registry) {
	reg.Add(&govarlink.RegistryInterface{
		Definition: "interface com.redhat.rhsm.testing.content.profile\n\ntype Metadata (\n    # The user agent string (e.g. \"rhc/5.4.3\")\n    user_agent: ?string,\n    # The correlation id\n    correlation_id: ?string,\n    # The locale string (e.g. en_US.UTF-8)\n    locale: ?string\n)\n\n# Any method in this interface can be used only in the situation, when the system is registered\nerror SystemNotRegistered()\n\n# Candlepin server does not support uploading of profile\nerror ProfileNotSupported()\n\n# Method for gathering and uploading combined rpm profile to candlepin server.\n# The combined profile will contain the list of installed rpms and the list of\n# enabled repositories (modules were removed from DNF5)\nmethod Send(\n    metadata: ?Metadata\n) -> (\n    success: bool\n)\n",
		Name:       "com.redhat.rhsm.testing.content.profile",
	}, h)
}
