// Code generated by go-varlink/varlinkgen. DO NOT EDIT.

package rhsmapi

import (
	"encoding/json"
	govarlink "github.com/emersion/go-varlink"
)

type Metadata struct {
	CorrelationId *string `json:"correlation_id,omitempty"`
	Locale        *string `json:"locale,omitempty"`
	UserAgent     *string `json:"user_agent,omitempty"`
}

type FailedServerResponseError struct {
	Message string `json:"message"`
}

func (err *FailedServerResponseError) Error() string {
	return "varlink call failed: com.redhat.rhsm.testing.FailedServerResponse"
}

type InvalidClientConnectionError struct {
	Message string `json:"message"`
}

func (err *InvalidClientConnectionError) Error() string {
	return "varlink call failed: com.redhat.rhsm.testing.InvalidClientConnection"
}

type IsRegisteredIn struct{}
type IsRegisteredOut struct {
	Registered bool `json:"registered"`
}

type PingIn struct {
	Metadata *Metadata `json:"metadata,omitempty"`
}
type PingOut struct {
	Status json.RawMessage `json:"status"`
}

type Client struct {
	*govarlink.Client
}

func unmarshalError(err error) error {
	verr, ok := err.(*govarlink.ClientError)
	if !ok {
		return err
	}
	var v error
	switch verr.Name {
	case "com.redhat.rhsm.testing.FailedServerResponse":
		v = new(FailedServerResponseError)
	case "com.redhat.rhsm.testing.InvalidClientConnection":
		v = new(InvalidClientConnectionError)
	default:
		return err
	}
	if err := json.Unmarshal(verr.Parameters, v); err != nil {
		return err
	}
	return v
}
func (c Client) IsRegistered(in *IsRegisteredIn) (*IsRegisteredOut, error) {
	if in == nil {
		in = new(IsRegisteredIn)
	}
	out := new(IsRegisteredOut)
	err := c.Client.Do("com.redhat.rhsm.testing.IsRegistered", in, out)
	return out, unmarshalError(err)
}
func (c Client) Ping(in *PingIn) (*PingOut, error) {
	if in == nil {
		in = new(PingIn)
	}
	out := new(PingOut)
	err := c.Client.Do("com.redhat.rhsm.testing.Ping", in, out)
	return out, unmarshalError(err)
}

type Backend interface {
	IsRegistered(*IsRegisteredIn) (*IsRegisteredOut, error)
	Ping(*PingIn) (*PingOut, error)
}

type Handler struct {
	Backend Backend
}

func marshalError(err error) error {
	var name string
	switch err.(type) {
	case *FailedServerResponseError:
		name = "com.redhat.rhsm.testing.FailedServerResponse"
	case *InvalidClientConnectionError:
		name = "com.redhat.rhsm.testing.InvalidClientConnection"
	default:
		return err
	}
	return &govarlink.ServerError{
		Name:       name,
		Parameters: err,
	}
}
func (h Handler) HandleVarlink(call *govarlink.ServerCall, req *govarlink.ServerRequest) error {
	var (
		out interface{}
		err error
	)
	switch req.Method {
	case "com.redhat.rhsm.testing.IsRegistered":
		in := new(IsRegisteredIn)
		if err := json.Unmarshal(req.Parameters, in); err != nil {
			return err
		}
		out, err = h.Backend.IsRegistered(in)
	case "com.redhat.rhsm.testing.Ping":
		in := new(PingIn)
		if err := json.Unmarshal(req.Parameters, in); err != nil {
			return err
		}
		out, err = h.Backend.Ping(in)
	default:
		err = &govarlink.ServerError{
			Name:       "org.varlink.service.MethodNotFound",
			Parameters: map[string]string{"method": req.Method},
		}
	}
	if err != nil {
		return marshalError(err)
	}
	return call.CloseWithReply(out)
}

func (h Handler) Register(reg *govarlink.Registry) {
	reg.Add(&govarlink.RegistryInterface{
		Definition: "# Testing interface for the main RHSM API\ninterface com.redhat.rhsm.testing\n\ntype Metadata (\n    # The user agent string (e.g. \"rhc/5.4.3\")\n    user_agent: ?string,\n    # The correlation id\n    correlation_id: ?string,\n    # The locale string (e.g. en_US.UTF-8)\n    locale: ?string\n)\n\n# Error returned, when it is not possible to initialize the client\nerror InvalidClientConnection(message: string)\n\n# Generic error related to the server response, when the server is not available\n# or the server response the exit code that is not successful\nerror FailedServerResponse(message: string)\n\n# Check if the candlepin server is available\nmethod Ping(\n    metadata: ?Metadata\n) -> (\n    # Raw JSON output of REST API call 'GET /status' to Candlepin server\n    status: object\n)\n\n# Method returns true, when system is registered. Otherwise, it returns false.\nmethod IsRegistered() -> (registered: bool)\n",
		Name:       "com.redhat.rhsm.testing",
	}, h)
}
