# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/"
    target-branch: "release-0.2"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/integration-tests"
    target-branch: "main"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/integration-tests"
    target-branch: "release-0.2"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "release-0.2"
    schedule:
      interval: "weekly"
