// Code generated by go-varlink/varlinkgen. DO NOT EDIT.

package contentapi

import (
	"encoding/json"
	govarlink "github.com/emersion/go-varlink"
)

type Metadata struct {
	CorrelationId *string `json:"correlation_id,omitempty"`
	Locale        *string `json:"locale,omitempty"`
	UserAgent     *string `json:"user_agent,omitempty"`
}

type ContentNotManagedError struct{}

func (err *ContentNotManagedError) Error() string {
	return "varlink call failed: com.redhat.rhsm.testing.content.ContentNotManaged"
}

type IOFailedError struct {
	Message string `json:"message"`
}

func (err *IOFailedError) Error() string {
	return "varlink call failed: com.redhat.rhsm.testing.content.IOFailed"
}

type SystemNotRegisteredError struct{}

func (err *SystemNotRegisteredError) Error() string {
	return "varlink call failed: com.redhat.rhsm.testing.content.SystemNotRegistered"
}

type RefreshIn struct {
	Force    bool      `json:"force"`
	Metadata *Metadata `json:"metadata,omitempty"`
}
type RefreshOut struct {
	Success bool `json:"success"`
}

type Client struct {
	*govarlink.Client
}

func unmarshalError(err error) error {
	verr, ok := err.(*govarlink.ClientError)
	if !ok {
		return err
	}
	var v error
	switch verr.Name {
	case "com.redhat.rhsm.testing.content.ContentNotManaged":
		v = new(ContentNotManagedError)
	case "com.redhat.rhsm.testing.content.IOFailed":
		v = new(IOFailedError)
	case "com.redhat.rhsm.testing.content.SystemNotRegistered":
		v = new(SystemNotRegisteredError)
	default:
		return err
	}
	if err := json.Unmarshal(verr.Parameters, v); err != nil {
		return err
	}
	return v
}
func (c Client) Refresh(in *RefreshIn) (*RefreshOut, error) {
	if in == nil {
		in = new(RefreshIn)
	}
	out := new(RefreshOut)
	err := c.Client.Do("com.redhat.rhsm.testing.content.Refresh", in, out)
	return out, unmarshalError(err)
}

type Backend interface {
	Refresh(*RefreshIn) (*RefreshOut, error)
}

type Handler struct {
	Backend Backend
}

func marshalError(err error) error {
	var name string
	switch err.(type) {
	case *ContentNotManagedError:
		name = "com.redhat.rhsm.testing.content.ContentNotManaged"
	case *IOFailedError:
		name = "com.redhat.rhsm.testing.content.IOFailed"
	case *SystemNotRegisteredError:
		name = "com.redhat.rhsm.testing.content.SystemNotRegistered"
	default:
		return err
	}
	return &govarlink.ServerError{
		Name:       name,
		Parameters: err,
	}
}
func (h Handler) HandleVarlink(call *govarlink.ServerCall, req *govarlink.ServerRequest) error {
	var (
		out interface{}
		err error
	)
	switch req.Method {
	case "com.redhat.rhsm.testing.content.Refresh":
		in := new(RefreshIn)
		if err := json.Unmarshal(req.Parameters, in); err != nil {
			return err
		}
		out, err = h.Backend.Refresh(in)
	default:
		err = &govarlink.ServerError{
			Name:       "org.varlink.service.MethodNotFound",
			Parameters: map[string]string{"method": req.Method},
		}
	}
	if err != nil {
		return marshalError(err)
	}
	return call.CloseWithReply(out)
}

func (h Handler) Register(reg *govarlink.Registry) {
	reg.Add(&govarlink.RegistryInterface{
		Definition: "interface com.redhat.rhsm.testing.content\n\ntype Metadata (\n    # The user agent string (e.g. \"rhc/0.5.3\")\n    user_agent: ?string,\n    # The correlation id\n    correlation_id: ?string,\n    # The locale string (e.g. en_US.UTF-8)\n    locale: ?string\n)\n\n# Many methods in this interface can be used only in the situation, when the system is registered\nerror SystemNotRegistered()\n\n# This error is used, when rhsm is configured to not manage content\nerror ContentNotManaged()\n\n# This error is returned when a local file system operation fails\nerror IOFailed(message: string)\n\n# Try to refresh entitlement certificate, when needed, and update\n# redhat.repo file accordingly. The content (redhat.repo file) is\n# generated from the SCA entitlement certificate. When force is true,\n# the entitlement certificate is force recreated.\nmethod Refresh(\n    force: bool,\n    metadata: ?Metadata\n) -> (\n    success: bool\n)\n",
		Name:       "com.redhat.rhsm.testing.content",
	}, h)
}
