upstream_package_name: rhc
downstream_package_name: rhc
specfile_path: rhc.spec

srpm_build_deps:
  - gawk
  - git-core
  - golang
  - make
  - 'pkgconfig(dbus-1)'
  - 'pkgconfig(systemd)'
  - rpm-build

actions:
  post-upstream-clone:
    - bash -c 'make rhc.spec dist'
  get-current-version:
    - awk '/^Version:/ {print $2;}' ./rhc.spec
  create-archive:
    - bash -c 'echo rhc-*.tar.*'
  fix-spec-file:
    - echo 'nothing to fix'

jobs:
  - job: copr_build
    trigger: pull_request
    additional_repos:
      - "copr://@yggdrasil/latest"
    targets:
      - centos-stream-8
      - centos-stream-9
      - fedora-all
      - rhel-8
      - rhel-9

  - job: copr_build
    trigger: commit
    additional_repos:
      - "copr://@yggdrasil/latest"
    branch: main
    owner: "@yggdrasil"
    project: latest
    targets:
      - centos-stream-8
      - centos-stream-9
      - fedora-all
      - rhel-8
      - rhel-9
