upstream_package_name: rhc
downstream_package_name: rhc
specfile_path: builddir/dist/srpm/rhc.spec

srpm_build_deps:
  - gawk
  - git-core
  - golang
  - meson
  - "pkgconfig(bash-completion)"
  - "pkgconfig(dbus-1)"
  - "pkgconfig(systemd)"
  - "rpm_macro(forgemeta)"
  - rpm-build

actions:
  post-upstream-clone:
    - meson setup builddir -Dbuild_srpm=True -Dvendor=True --wipe
    - meson compile tarball -C builddir
  get-current-version:
    - awk '/^Version:/ {print $2;}' builddir/dist/srpm/rhc.spec
  create-archive:
    - bash -c 'echo builddir/dist/srpm/rhc-*.tar.*'
  fix-spec-file:
    - echo 'nothing to fix'

jobs:
  - job: copr_build
    trigger: pull_request
    additional_repos:
      - "copr://@yggdrasil/latest"
    targets:
      - centos-stream-9-aarch64
      - centos-stream-9-x86_64
      - centos-stream-10-aarch64
      - centos-stream-10-x86_64
      - fedora-all-aarch64
      - fedora-all-x86_64
      - rhel-9-aarch64
      - rhel-9-x86_64

  - job: copr_build
    trigger: commit
    additional_repos:
      - "copr://@yggdrasil/latest"
    branch: main
    owner: "@yggdrasil"
    project: latest
    targets:
      - centos-stream-9-aarch64
      - centos-stream-9-x86_64
      - centos-stream-10-aarch64
      - centos-stream-10-x86_64
      - fedora-all-aarch64
      - fedora-all-x86_64
      - rhel-9-aarch64
      - rhel-9-x86_64

  - job: tests
    trigger: pull_request
    identifier: "unit/centos-stream"
    targets:
      - centos-stream-9-aarch64
      - centos-stream-9-x86_64
      - centos-stream-10-aarch64
      - centos-stream-10-x86_64
    labels:
      - unit
    tf_extra_params:
      environments:
        - artifacts:
            - type: repository-file
              id: https://copr.fedorainfracloud.org/coprs/g/yggdrasil/latest/repo/centos-stream-$releasever/group_yggdrasil-latest-centos-stream-$releasever.repo

  - job: tests
    trigger: pull_request
    identifier: "unit/fedora"
    targets:
      - fedora-stable
      - fedora-rawhide
    labels:
      - unit
    tf_extra_params:
      environments:
        - artifacts:
            - type: repository-file
              id: https://copr.fedorainfracloud.org/coprs/g/yggdrasil/latest/repo/fedora-$releasever/group_yggdrasil-latest-fedora-$releasever.repo

  - job: tests
    trigger: pull_request
    identifier: "unit/rhel"
    targets:
      centos-stream-10-x86_64: # TODO: Change me back to RHEL
        distros:
          - RHEL-10-Nightly
    labels:
      - unit
    tf_extra_params:
      environments:
        - artifacts:
            - type: repository-file
              id: https://copr.fedorainfracloud.org/coprs/g/yggdrasil/latest/repo/rhel-$releasever/group_yggdrasil-latest-rhel-$releasever.repo
          settings:
            provisioning:
              tags:
                BusinessUnit: sst_csi_client_tools
    use_internal_tf: true
