specfile_path: rhc.spec

# List of files to synchronize from GitHub upstream to Fedora downstream
files_to_sync:
  - rhc.spec
  - .packit.yaml

# Dependencies for SRPM creation (i.e., make archive* targets)
srpm_build_deps:
  - git
  - go
  - make
  - rpm-build

# Hooks to overwrite default Packit behavior
actions:
  post-upstream-clone:
    # go-vendor-tools package is only available in Fedora repositories
    - bash -c 'source /etc/os-release && [ "$ID" = "fedora" ] && dnf install -y go-vendor-tools || true'
  get-current-version:
    # Extract version from the .spec file
    - bash -c 'rpmspec --query --queryformat "%{version}\n" rhc.spec'
  create-archive:
    - bash -c 'make archive archive-deps'
    # Packit expects a single archive was created
    #  https://packit.dev/docs/configuration/examples#custom-archive-creation-for-srpm
    - bash -c "ls -1 ./rhc-*.tar.gz | head -n 1"

jobs:
  - job: copr_build
    trigger: pull_request
    targets:
      - fedora-development-aarch64
      - fedora-development-x86_64
      - centos-stream-10-aarch64
      - centos-stream-10-x86_64
      - rhel-10-aarch64
      - rhel-10-x86_64

  - job: copr_build
    trigger: commit
    targets:
      - fedora-development-aarch64
      - fedora-development-x86_64
      - centos-stream-10-aarch64
      - centos-stream-10-x86_64
      - rhel-10-aarch64
      - rhel-10-x86_64

  - job: tests
    trigger: pull_request
    identifier: "integration-tests/centos-stream"
    targets:
      - centos-stream-10-aarch64
      - centos-stream-10-x86_64
    labels:
      - unit

  - job: tests
    trigger: pull_request
    identifier: "integration-tests/fedora"
    targets:
      - fedora-development-aarch64
      - fedora-development-x86_64
    labels:
      - unit

  - job: tests
    trigger: pull_request
    identifier: "integration-tests/rhel"
    targets:
      rhel-10-aarch64:
        distros: [RHEL-10-Nightly]
      rhel-10-x86_64:
        distros: [RHEL-10-Nightly]
    labels:
      - unit
    tf_extra_params:
      environments:
        settings:
          provisioning:
            tags:
              BusinessUnit: sst_csi_client_tools
    use_internal_tf: true
