specfile_path: rhc.spec

# List of files to synchronize from GitHub upstream to Fedora downstream
files_to_sync:
  - dnf5.spec
  - .packit.yml

srpm_build_deps:
  - gawk
  - golang
  - dbus-x11
  - "pkgconfig(bash-completion)"
  - "pkgconfig(dbus-1)"
  - rpm-build
  - "go-vendor-tools"

# Hooks to overwrite default Packit behavior
actions:
  # Extract version from the .spec file
  get-current-version:
    - bash -c 'rpmspec --query --queryformat "%{version}\n" rhc.spec'
  # Packit expects a single archive to be created
  #  https://packit.dev/docs/configuration/examples#custom-archive-creation-for-srpm
  create-archive:
    - make archive
    - bash -c "ls -1 ./rhc-*.tar.gz | head -n 1"

jobs:
  - job: copr_build
    trigger: pull_request
    additional_repos:
      - "copr://@yggdrasil/latest"
      - "copr://@go-sig/go-vendor-tools-dev"
    targets:
      - centos-stream-10-aarch64
      - centos-stream-10-x86_64
      - centos-stream-10-ppc64le
      - centos-stream-10-s390x
      - fedora-all-aarch64
      - fedora-all-x86_64
      - fedora-all-ppc64le
      - fedora-all-s390x
      - rhel-10-aarch64
      - rhel-10-x86_64
      - rhel-10-ppc64le
      - rhel-10-s390x

  - job: copr_build
    trigger: commit
    additional_repos:
      - "copr://@yggdrasil/latest"
      - "copr://@go-sig/go-vendor-tools-dev"
    branch: main
    owner: "@yggdrasil"
    project: latest
    targets:
      - centos-stream-10-aarch64
      - centos-stream-10-x86_64
      - centos-stream-10-ppc64le
      - centos-stream-10-s390x
      - fedora-all-aarch64
      - fedora-all-x86_64
      - fedora-all-ppc64le
      - fedora-all-s390x
      - rhel-10-aarch64
      - rhel-10-x86_64
      - rhel-10-s390x
      - rhel-10-ppc64le

  - job: tests
    trigger: pull_request
    identifier: "unit/centos-stream"
    targets:
      - centos-stream-10-aarch64
      - centos-stream-10-x86_64
    labels:
      - unit
    tf_extra_params:
      environments:
        - artifacts:
            - type: repository-file
              id: https://copr.fedorainfracloud.org/coprs/g/yggdrasil/latest/repo/centos-stream-$releasever/group_yggdrasil-latest-centos-stream-$releasever.repo

  - job: tests
    trigger: pull_request
    identifier: "unit/fedora"
    targets:
      - fedora-stable
      - fedora-rawhide
    labels:
      - unit
    tf_extra_params:
      environments:
        - artifacts:
            - type: repository-file
              id: https://copr.fedorainfracloud.org/coprs/g/yggdrasil/latest/repo/fedora-$releasever/group_yggdrasil-latest-fedora-$releasever.repo

  - job: tests
    trigger: pull_request
    identifier: "unit/rhel"
    targets:
      rhel-10-x86_64:
        distros:
          - RHEL-10-Nightly
    labels:
      - unit
    tf_extra_params:
      environments:
        - artifacts:
            - type: repository-file
              id: https://copr.fedorainfracloud.org/coprs/g/yggdrasil/latest/repo/rhel-$releasever/group_yggdrasil-latest-rhel-$releasever.repo
          settings:
            provisioning:
              tags:
                BusinessUnit: sst_csi_client_tools
    use_internal_tf: true
