// Code generated by go-varlink/varlinkgen. DO NOT EDIT.

package overrideapi

import (
	"encoding/json"
	govarlink "github.com/emersion/go-varlink"
)

type ContentOverride struct {
	ContentLabel string  `json:"content_label"`
	Created      *string `json:"created,omitempty"`
	Name         string  `json:"name"`
	Updated      *string `json:"updated,omitempty"`
	Value        string  `json:"value"`
}
type Metadata struct {
	CorrelationId *string `json:"correlation_id,omitempty"`
	Locale        *string `json:"locale,omitempty"`
	UserAgent     *string `json:"user_agent,omitempty"`
}

type ContentNotManagedError struct{}

func (err *ContentNotManagedError) Error() string {
	return "varlink call failed: com.redhat.rhsm.testing.content.override.ContentNotManaged"
}

type SystemNotRegisteredError struct{}

func (err *SystemNotRegisteredError) Error() string {
	return "varlink call failed: com.redhat.rhsm.testing.content.override.SystemNotRegistered"
}

type DownloadIn struct {
	Metadata *Metadata `json:"metadata,omitempty"`
}
type DownloadOut struct {
	ContentOverrides []ContentOverride `json:"content_overrides"`
}

type UploadIn struct {
	Metadata *Metadata `json:"metadata,omitempty"`
}
type UploadOut struct {
	Success bool `json:"success"`
}

type Client struct {
	*govarlink.Client
}

func unmarshalError(err error) error {
	verr, ok := err.(*govarlink.ClientError)
	if !ok {
		return err
	}
	var v error
	switch verr.Name {
	case "com.redhat.rhsm.testing.content.override.ContentNotManaged":
		v = new(ContentNotManagedError)
	case "com.redhat.rhsm.testing.content.override.SystemNotRegistered":
		v = new(SystemNotRegisteredError)
	default:
		return err
	}
	if err := json.Unmarshal(verr.Parameters, v); err != nil {
		return err
	}
	return v
}
func (c Client) Download(in *DownloadIn) (*DownloadOut, error) {
	if in == nil {
		in = new(DownloadIn)
	}
	out := new(DownloadOut)
	err := c.Client.Do("com.redhat.rhsm.testing.content.override.Download", in, out)
	return out, unmarshalError(err)
}
func (c Client) Upload(in *UploadIn) (*UploadOut, error) {
	if in == nil {
		in = new(UploadIn)
	}
	out := new(UploadOut)
	err := c.Client.Do("com.redhat.rhsm.testing.content.override.Upload", in, out)
	return out, unmarshalError(err)
}

type Backend interface {
	Download(*DownloadIn) (*DownloadOut, error)
	Upload(*UploadIn) (*UploadOut, error)
}

type Handler struct {
	Backend Backend
}

func marshalError(err error) error {
	var name string
	switch err.(type) {
	case *ContentNotManagedError:
		name = "com.redhat.rhsm.testing.content.override.ContentNotManaged"
	case *SystemNotRegisteredError:
		name = "com.redhat.rhsm.testing.content.override.SystemNotRegistered"
	default:
		return err
	}
	return &govarlink.ServerError{
		Name:       name,
		Parameters: err,
	}
}
func (h Handler) HandleVarlink(call *govarlink.ServerCall, req *govarlink.ServerRequest) error {
	var (
		out interface{}
		err error
	)
	switch req.Method {
	case "com.redhat.rhsm.testing.content.override.Download":
		in := new(DownloadIn)
		if err := json.Unmarshal(req.Parameters, in); err != nil {
			return err
		}
		out, err = h.Backend.Download(in)
	case "com.redhat.rhsm.testing.content.override.Upload":
		in := new(UploadIn)
		if err := json.Unmarshal(req.Parameters, in); err != nil {
			return err
		}
		out, err = h.Backend.Upload(in)
	default:
		err = &govarlink.ServerError{
			Name:       "org.varlink.service.MethodNotFound",
			Parameters: map[string]string{"method": req.Method},
		}
	}
	if err != nil {
		return marshalError(err)
	}
	return call.CloseWithReply(out)
}

func (h Handler) Register(reg *govarlink.Registry) {
	reg.Add(&govarlink.RegistryInterface{
		Definition: "interface com.redhat.rhsm.testing.content.override\n\ntype Metadata (\n    # The user agent string (e.g. \"rhc/5.4.3\")\n    user_agent: ?string,\n    # The correlation id\n    correlation_id: ?string,\n    # The locale string (e.g. en_US.UTF-8)\n    locale: ?string\n)\n\n# Content override representing repo override\ntype ContentOverride (\n    created: ?string,\n    updated: ?string,\n    content_label: string,\n    name: string,\n    value: string\n)\n\n# Many methods in this interface can be used only in the situation, when the system is registered\nerror SystemNotRegistered()\n\n# This error is used, when rhsm is configured to not manage content\nerror ContentNotManaged()\n\n# Get content overrides from the candlepin server\n# When system is not registered, then return error SystemNotRegistered\nmethod Download(\n    metadata: ?Metadata\n) -> (\n    content_overrides: []ContentOverride\n)\n\n# Read current repo-overrides in /etc/dnf/repo.override.d/ and convert it to\n# content overrides and send this document to candlepin server\nmethod Upload(\n    metadata: ?Metadata\n) -> (\n    success: bool\n)\n",
		Name:       "com.redhat.rhsm.testing.content.override",
	}, h)
}
