ARG IMAGE=registry.redhat.io/rhel9/rhel-bootc:9.7-1765350338
FROM $IMAGE

COPY install-test-deps.sh /install-test-deps.sh
RUN sh /install-test-deps.sh
RUN touch /test-deps-installed
RUN bootc container lint
