// Code generated by go-varlink/varlinkgen. DO NOT EDIT.

package releaseapi

import (
	"encoding/json"
	govarlink "github.com/emersion/go-varlink"
)

type Metadata struct {
	CorrelationId *string `json:"correlation_id,omitempty"`
	Locale        *string `json:"locale,omitempty"`
	UserAgent     *string `json:"user_agent,omitempty"`
}

type SystemNotRegisteredError struct{}

func (err *SystemNotRegisteredError) Error() string {
	return "varlink call failed: com.redhat.rhsm.testing.content.release.SystemNotRegistered"
}

type DownloadIn struct {
	Metadata *Metadata `json:"metadata,omitempty"`
}
type DownloadOut struct {
	Release string `json:"release"`
}

type GetAvailableReleasesIn struct {
	Metadata *Metadata `json:"metadata,omitempty"`
}
type GetAvailableReleasesOut struct {
	Releases []string `json:"releases"`
}

type GetCurrentReleaseIn struct{}
type GetCurrentReleaseOut struct {
	Release *string `json:"release,omitempty"`
}

type SetReleaseIn struct {
	Metadata *Metadata `json:"metadata,omitempty"`
	Release  string    `json:"release"`
}
type SetReleaseOut struct {
	Success bool `json:"success"`
}

type Client struct {
	*govarlink.Client
}

func unmarshalError(err error) error {
	verr, ok := err.(*govarlink.ClientError)
	if !ok {
		return err
	}
	var v error
	switch verr.Name {
	case "com.redhat.rhsm.testing.content.release.SystemNotRegistered":
		v = new(SystemNotRegisteredError)
	default:
		return err
	}
	if err := json.Unmarshal(verr.Parameters, v); err != nil {
		return err
	}
	return v
}
func (c Client) Download(in *DownloadIn) (*DownloadOut, error) {
	if in == nil {
		in = new(DownloadIn)
	}
	out := new(DownloadOut)
	err := c.Client.Do("com.redhat.rhsm.testing.content.release.Download", in, out)
	return out, unmarshalError(err)
}
func (c Client) GetAvailableReleases(in *GetAvailableReleasesIn) (*GetAvailableReleasesOut, error) {
	if in == nil {
		in = new(GetAvailableReleasesIn)
	}
	out := new(GetAvailableReleasesOut)
	err := c.Client.Do("com.redhat.rhsm.testing.content.release.GetAvailableReleases", in, out)
	return out, unmarshalError(err)
}
func (c Client) GetCurrentRelease(in *GetCurrentReleaseIn) (*GetCurrentReleaseOut, error) {
	if in == nil {
		in = new(GetCurrentReleaseIn)
	}
	out := new(GetCurrentReleaseOut)
	err := c.Client.Do("com.redhat.rhsm.testing.content.release.GetCurrentRelease", in, out)
	return out, unmarshalError(err)
}
func (c Client) SetRelease(in *SetReleaseIn) (*SetReleaseOut, error) {
	if in == nil {
		in = new(SetReleaseIn)
	}
	out := new(SetReleaseOut)
	err := c.Client.Do("com.redhat.rhsm.testing.content.release.SetRelease", in, out)
	return out, unmarshalError(err)
}

type Backend interface {
	Download(*DownloadIn) (*DownloadOut, error)
	GetAvailableReleases(*GetAvailableReleasesIn) (*GetAvailableReleasesOut, error)
	GetCurrentRelease(*GetCurrentReleaseIn) (*GetCurrentReleaseOut, error)
	SetRelease(*SetReleaseIn) (*SetReleaseOut, error)
}

type Handler struct {
	Backend Backend
}

func marshalError(err error) error {
	var name string
	switch err.(type) {
	case *SystemNotRegisteredError:
		name = "com.redhat.rhsm.testing.content.release.SystemNotRegistered"
	default:
		return err
	}
	return &govarlink.ServerError{
		Name:       name,
		Parameters: err,
	}
}
func (h Handler) HandleVarlink(call *govarlink.ServerCall, req *govarlink.ServerRequest) error {
	var (
		out interface{}
		err error
	)
	switch req.Method {
	case "com.redhat.rhsm.testing.content.release.Download":
		in := new(DownloadIn)
		if err := json.Unmarshal(req.Parameters, in); err != nil {
			return err
		}
		out, err = h.Backend.Download(in)
	case "com.redhat.rhsm.testing.content.release.GetAvailableReleases":
		in := new(GetAvailableReleasesIn)
		if err := json.Unmarshal(req.Parameters, in); err != nil {
			return err
		}
		out, err = h.Backend.GetAvailableReleases(in)
	case "com.redhat.rhsm.testing.content.release.GetCurrentRelease":
		in := new(GetCurrentReleaseIn)
		if err := json.Unmarshal(req.Parameters, in); err != nil {
			return err
		}
		out, err = h.Backend.GetCurrentRelease(in)
	case "com.redhat.rhsm.testing.content.release.SetRelease":
		in := new(SetReleaseIn)
		if err := json.Unmarshal(req.Parameters, in); err != nil {
			return err
		}
		out, err = h.Backend.SetRelease(in)
	default:
		err = &govarlink.ServerError{
			Name:       "org.varlink.service.MethodNotFound",
			Parameters: map[string]string{"method": req.Method},
		}
	}
	if err != nil {
		return marshalError(err)
	}
	return call.CloseWithReply(out)
}

func (h Handler) Register(reg *govarlink.Registry) {
	reg.Add(&govarlink.RegistryInterface{
		Definition: "interface com.redhat.rhsm.testing.content.release\n\ntype Metadata (\n    # The user agent string (e.g. \"rhc/5.4.3\")\n    user_agent: ?string,\n    # The correlation id\n    correlation_id: ?string,\n    # The locale string (e.g. en_US.UTF-8)\n    locale: ?string\n)\n\n# Many methods in this interface can be used only in the situation, when the system is registered\nerror SystemNotRegistered()\n\n# Get release from the candlepin server\n# When system is not registered, then return error SystemNotRegistered\nmethod Download(\n    metadata: ?Metadata\n) -> (\n    release: string\n)\n\n# Return current release, when it is set. Otherwise, return nul\nmethod GetCurrentRelease() -> (\n    release: ?string\n)\n\n# Return the list of available releases\nmethod GetAvailableReleases(\n    metadata: ?Metadata\n) -> (\n    releases: []string\n)\n\n# Try to set release locally and when the system is registered,\n# then send the release to candlepin server\nmethod SetRelease(\n   release: string,\n   metadata: ?Metadata\n) -> (\n    success: bool\n)\n",
		Name:       "com.redhat.rhsm.testing.content.release",
	}, h)
}
