// Code generated by go-varlink/varlinkgen. DO NOT EDIT.

package internalapi

import (
	"encoding/json"
	govarlink "github.com/emersion/go-varlink"
)

type InvalidParameterError struct {
	Parameter string `json:"parameter"`
}

func (err *InvalidParameterError) Error() string {
	return "varlink call failed: com.redhat.rhc.internal.InvalidParameter"
}

type FooIn struct{}
type FooOut struct {
	Output string `json:"output"`
}

type TestIn struct {
	Input string `json:"input"`
}
type TestOut struct {
	Output string `json:"output"`
}

type Client struct {
	*govarlink.Client
}

func unmarshalError(err error) error {
	verr, ok := err.(*govarlink.ClientError)
	if !ok {
		return err
	}
	var v error
	switch verr.Name {
	case "com.redhat.rhc.internal.InvalidParameter":
		v = new(InvalidParameterError)
	default:
		return err
	}
	if err := json.Unmarshal(verr.Parameters, v); err != nil {
		return err
	}
	return v
}
func (c Client) Foo(in *FooIn) (*FooOut, error) {
	if in == nil {
		in = new(FooIn)
	}
	out := new(FooOut)
	err := c.Client.Do("com.redhat.rhc.internal.Foo", in, out)
	return out, unmarshalError(err)
}
func (c Client) Test(in *TestIn) (*TestOut, error) {
	if in == nil {
		in = new(TestIn)
	}
	out := new(TestOut)
	err := c.Client.Do("com.redhat.rhc.internal.Test", in, out)
	return out, unmarshalError(err)
}

type Backend interface {
	Foo(*FooIn) (*FooOut, error)
	Test(*TestIn) (*TestOut, error)
}

type Handler struct {
	Backend Backend
}

func marshalError(err error) error {
	var name string
	switch err.(type) {
	case *InvalidParameterError:
		name = "com.redhat.rhc.internal.InvalidParameter"
	default:
		return err
	}
	return &govarlink.ServerError{
		Name:       name,
		Parameters: err,
	}
}
func (h Handler) HandleVarlink(call *govarlink.ServerCall, req *govarlink.ServerRequest) error {
	var (
		out interface{}
		err error
	)
	switch req.Method {
	case "com.redhat.rhc.internal.Foo":
		in := new(FooIn)
		if err := json.Unmarshal(req.Parameters, in); err != nil {
			return err
		}
		out, err = h.Backend.Foo(in)
	case "com.redhat.rhc.internal.Test":
		in := new(TestIn)
		if err := json.Unmarshal(req.Parameters, in); err != nil {
			return err
		}
		out, err = h.Backend.Test(in)
	default:
		err = &govarlink.ServerError{
			Name:       "org.varlink.service.MethodNotFound",
			Parameters: map[string]string{"method": req.Method},
		}
	}
	if err != nil {
		return marshalError(err)
	}
	return call.CloseWithReply(out)
}

func (h Handler) Register(reg *govarlink.Registry) {
	reg.Add(&govarlink.RegistryInterface{
		Definition: "interface com.redhat.rhc.internal\n# Internal API for rhc-server\n# This API is temporary and unstable\n\n# Generic error for invalid parameters\nerror InvalidParameter (parameter: string)\n\n# Test method - returns the input string as-is\nmethod Test(input: string) -> (output: string)\n\n# Foo method - does not have any parameter\nmethod Foo() -> (output: string)\n",
		Name:       "com.redhat.rhc.internal",
	}, h)
}
