// Code generated by go-varlink/varlinkgen. DO NOT EDIT.

package collectorapi

import (
	"encoding/json"
	govarlink "github.com/emersion/go-varlink"
)

type CollectorInfo struct {
	ConfigPath  string  `json:"config_path"`
	Feature     *string `json:"feature,omitempty"`
	Id          string  `json:"id"`
	LastRun     *int    `json:"last_run,omitempty"`
	Name        string  `json:"name"`
	NextRun     *int    `json:"next_run,omitempty"`
	ServiceName string  `json:"service_name"`
	TimerName   string  `json:"timer_name"`
}

type InvalidParameterError struct {
	Parameter string `json:"parameter"`
}

func (err *InvalidParameterError) Error() string {
	return "varlink call failed: com.redhat.rhc.collector.InvalidParameter"
}

type NoSuchCollectorError struct {
	Id string `json:"id"`
}

func (err *NoSuchCollectorError) Error() string {
	return "varlink call failed: com.redhat.rhc.collector.NoSuchCollector"
}

type InfoIn struct {
	Id string `json:"id"`
}
type InfoOut struct {
	Info CollectorInfo `json:"info"`
}

type ListIn struct{}
type ListOut struct {
	Collectors []CollectorInfo `json:"collectors"`
}

type Client struct {
	*govarlink.Client
}

func unmarshalError(err error) error {
	verr, ok := err.(*govarlink.ClientError)
	if !ok {
		return err
	}
	var v error
	switch verr.Name {
	case "com.redhat.rhc.collector.InvalidParameter":
		v = new(InvalidParameterError)
	case "com.redhat.rhc.collector.NoSuchCollector":
		v = new(NoSuchCollectorError)
	default:
		return err
	}
	if err := json.Unmarshal(verr.Parameters, v); err != nil {
		return err
	}
	return v
}
func (c Client) Info(in *InfoIn) (*InfoOut, error) {
	if in == nil {
		in = new(InfoIn)
	}
	out := new(InfoOut)
	err := c.Client.Do("com.redhat.rhc.collector.Info", in, out)
	return out, unmarshalError(err)
}
func (c Client) List(in *ListIn) (*ListOut, error) {
	if in == nil {
		in = new(ListIn)
	}
	out := new(ListOut)
	err := c.Client.Do("com.redhat.rhc.collector.List", in, out)
	return out, unmarshalError(err)
}

type Backend interface {
	Info(*InfoIn) (*InfoOut, error)
	List(*ListIn) (*ListOut, error)
}

type Handler struct {
	Backend Backend
}

func marshalError(err error) error {
	var name string
	switch err.(type) {
	case *InvalidParameterError:
		name = "com.redhat.rhc.collector.InvalidParameter"
	case *NoSuchCollectorError:
		name = "com.redhat.rhc.collector.NoSuchCollector"
	default:
		return err
	}
	return &govarlink.ServerError{
		Name:       name,
		Parameters: err,
	}
}
func (h Handler) HandleVarlink(call *govarlink.ServerCall, req *govarlink.ServerRequest) error {
	var (
		out interface{}
		err error
	)
	switch req.Method {
	case "com.redhat.rhc.collector.Info":
		in := new(InfoIn)
		if err := json.Unmarshal(req.Parameters, in); err != nil {
			return err
		}
		out, err = h.Backend.Info(in)
	case "com.redhat.rhc.collector.List":
		in := new(ListIn)
		if err := json.Unmarshal(req.Parameters, in); err != nil {
			return err
		}
		out, err = h.Backend.List(in)
	default:
		err = &govarlink.ServerError{
			Name:       "org.varlink.service.MethodNotFound",
			Parameters: map[string]string{"method": req.Method},
		}
	}
	if err != nil {
		return marshalError(err)
	}
	return call.CloseWithReply(out)
}

func (h Handler) Register(reg *govarlink.Registry) {
	reg.Add(&govarlink.RegistryInterface{
		Definition: "interface com.redhat.rhc.collector\n# Collector API for rhc-server\n# This API is temporary and unstable\n\n# Generic error for invalid parameters\nerror InvalidParameter (parameter: string)\n\n# Error when a collector is not found\nerror NoSuchCollector (id: string)\n\n# Detailed collector information\ntype CollectorInfo (\n    id: string,\n    name: string,\n    feature: ?string,\n    last_run: ?int,\n    next_run: ?int,\n    config_path: string,\n    service_name: string,\n    timer_name: string\n)\n\n# List all available collectors with full details\nmethod List() -> (collectors: []CollectorInfo)\n\n# Get detailed information about a specific collector\nmethod Info(id: string) -> (info: CollectorInfo)\n",
		Name:       "com.redhat.rhc.collector",
	}, h)
}
