// Code generated by go-varlink/varlinkgen. DO NOT EDIT.

package consumerapi

import (
	"encoding/json"
	govarlink "github.com/emersion/go-varlink"
)

type SystemNotRegisteredError struct{}

func (err *SystemNotRegisteredError) Error() string {
	return "varlink call failed: com.redhat.rhc.testing.rhsm.consumer.SystemNotRegistered"
}

type GetEnvironmentsIn struct{}
type GetEnvironmentsOut struct {
	Environments []json.RawMessage `json:"environments"`
}

type GetOrganizationIn struct{}
type GetOrganizationOut struct {
	Org json.RawMessage `json:"org"`
}

type GetUUIDIn struct{}
type GetUUIDOut struct {
	Uuid string `json:"uuid"`
}

type Client struct {
	*govarlink.Client
}

func unmarshalError(err error) error {
	verr, ok := err.(*govarlink.ClientError)
	if !ok {
		return err
	}
	var v error
	switch verr.Name {
	case "com.redhat.rhc.testing.rhsm.consumer.SystemNotRegistered":
		v = new(SystemNotRegisteredError)
	default:
		return err
	}
	if err := json.Unmarshal(verr.Parameters, v); err != nil {
		return err
	}
	return v
}
func (c Client) GetEnvironments(in *GetEnvironmentsIn) (*GetEnvironmentsOut, error) {
	if in == nil {
		in = new(GetEnvironmentsIn)
	}
	out := new(GetEnvironmentsOut)
	err := c.Client.Do("com.redhat.rhc.testing.rhsm.consumer.GetEnvironments", in, out)
	return out, unmarshalError(err)
}
func (c Client) GetOrganization(in *GetOrganizationIn) (*GetOrganizationOut, error) {
	if in == nil {
		in = new(GetOrganizationIn)
	}
	out := new(GetOrganizationOut)
	err := c.Client.Do("com.redhat.rhc.testing.rhsm.consumer.GetOrganization", in, out)
	return out, unmarshalError(err)
}
func (c Client) GetUUID(in *GetUUIDIn) (*GetUUIDOut, error) {
	if in == nil {
		in = new(GetUUIDIn)
	}
	out := new(GetUUIDOut)
	err := c.Client.Do("com.redhat.rhc.testing.rhsm.consumer.GetUUID", in, out)
	return out, unmarshalError(err)
}

type Backend interface {
	GetEnvironments(*GetEnvironmentsIn) (*GetEnvironmentsOut, error)
	GetOrganization(*GetOrganizationIn) (*GetOrganizationOut, error)
	GetUUID(*GetUUIDIn) (*GetUUIDOut, error)
}

type Handler struct {
	Backend Backend
}

func marshalError(err error) error {
	var name string
	switch err.(type) {
	case *SystemNotRegisteredError:
		name = "com.redhat.rhc.testing.rhsm.consumer.SystemNotRegistered"
	default:
		return err
	}
	return &govarlink.ServerError{
		Name:       name,
		Parameters: err,
	}
}
func (h Handler) HandleVarlink(call *govarlink.ServerCall, req *govarlink.ServerRequest) error {
	var (
		out interface{}
		err error
	)
	switch req.Method {
	case "com.redhat.rhc.testing.rhsm.consumer.GetEnvironments":
		in := new(GetEnvironmentsIn)
		if err := json.Unmarshal(req.Parameters, in); err != nil {
			return err
		}
		out, err = h.Backend.GetEnvironments(in)
	case "com.redhat.rhc.testing.rhsm.consumer.GetOrganization":
		in := new(GetOrganizationIn)
		if err := json.Unmarshal(req.Parameters, in); err != nil {
			return err
		}
		out, err = h.Backend.GetOrganization(in)
	case "com.redhat.rhc.testing.rhsm.consumer.GetUUID":
		in := new(GetUUIDIn)
		if err := json.Unmarshal(req.Parameters, in); err != nil {
			return err
		}
		out, err = h.Backend.GetUUID(in)
	default:
		err = &govarlink.ServerError{
			Name:       "org.varlink.service.MethodNotFound",
			Parameters: map[string]string{"method": req.Method},
		}
	}
	if err != nil {
		return marshalError(err)
	}
	return call.CloseWithReply(out)
}

func (h Handler) Register(reg *govarlink.Registry) {
	reg.Add(&govarlink.RegistryInterface{
		Definition: "# Consumer interface for the RHSM API\n# Any method in this interface can be used only when the system is registered\ninterface com.redhat.rhc.testing.rhsm.consumer\n\n# Error returned when a method is called on an unregistered system\nerror SystemNotRegistered()\n\n# Return UUID from installed consumer certificate\nmethod GetUUID() -> (\n    uuid: string\n)\n\n# Return organization that the registered system belongs to.\n# The object mirrors Candlepin owner fields (e.g. key, displayName, id).\nmethod GetOrganization() -> (\n    org: object\n)\n\n# Return environments assigned to the registered consumer.\n# Returns an empty list when no environments are assigned.\nmethod GetEnvironments() -> (\n    environments: []object\n)\n",
		Name:       "com.redhat.rhc.testing.rhsm.consumer",
	}, h)
}
