// Code generated by go-varlink/varlinkgen. DO NOT EDIT.

package consumerapi

import (
	"encoding/json"
	govarlink "github.com/emersion/go-varlink"
)

type Environment struct {
	ContentPrefix      *string               `json:"contentPrefix,omitempty"`
	Created            *string               `json:"created,omitempty"`
	Description        *string               `json:"description,omitempty"`
	EnvironmentContent *[]EnvironmentContent `json:"environmentContent,omitempty"`
	Id                 string                `json:"id"`
	Name               *string               `json:"name,omitempty"`
	Owner              *EnvironmentOwner     `json:"owner,omitempty"`
	Type               *string               `json:"type,omitempty"`
	Updated            *string               `json:"updated,omitempty"`
}
type EnvironmentContent struct {
	ContentId string `json:"contentId"`
	Enabled   bool   `json:"enabled"`
}
type EnvironmentOwner struct {
	ContentAccessMode *string `json:"contentAccessMode,omitempty"`
	DisplayName       *string `json:"displayName,omitempty"`
	Href              *string `json:"href,omitempty"`
	Id                string  `json:"id"`
	Key               *string `json:"key,omitempty"`
}
type Organization struct {
	AutobindDisabled           *bool   `json:"autobindDisabled,omitempty"`
	AutobindHypervisorDisabled *bool   `json:"autobindHypervisorDisabled,omitempty"`
	ContentAccessMode          *string `json:"contentAccessMode,omitempty"`
	ContentAccessModeList      *string `json:"contentAccessModeList,omitempty"`
	ContentPrefix              *string `json:"contentPrefix,omitempty"`
	Created                    *string `json:"created,omitempty"`
	DefaultServiceLevel        *string `json:"defaultServiceLevel,omitempty"`
	DisplayName                *string `json:"displayName,omitempty"`
	Id                         string  `json:"id"`
	Key                        string  `json:"key"`
	LastRefreshed              *string `json:"lastRefreshed,omitempty"`
	LogLevel                   *string `json:"logLevel,omitempty"`
	Updated                    *string `json:"updated,omitempty"`
}

type SystemNotRegisteredError struct{}

func (err *SystemNotRegisteredError) Error() string {
	return "varlink call failed: com.redhat.rhc.testing.rhsm.consumer.SystemNotRegistered"
}

type GetEnvironmentsIn struct{}
type GetEnvironmentsOut struct {
	Environments []Environment `json:"environments"`
}

type GetOrganizationIn struct{}
type GetOrganizationOut struct {
	Org Organization `json:"org"`
}

type GetUUIDIn struct{}
type GetUUIDOut struct {
	Uuid string `json:"uuid"`
}

type Client struct {
	*govarlink.Client
}

func unmarshalError(err error) error {
	verr, ok := err.(*govarlink.ClientError)
	if !ok {
		return err
	}
	var v error
	switch verr.Name {
	case "com.redhat.rhc.testing.rhsm.consumer.SystemNotRegistered":
		v = new(SystemNotRegisteredError)
	default:
		return err
	}
	if err := json.Unmarshal(verr.Parameters, v); err != nil {
		return err
	}
	return v
}
func (c Client) GetEnvironments(in *GetEnvironmentsIn) (*GetEnvironmentsOut, error) {
	if in == nil {
		in = new(GetEnvironmentsIn)
	}
	out := new(GetEnvironmentsOut)
	err := c.Client.Do("com.redhat.rhc.testing.rhsm.consumer.GetEnvironments", in, out)
	return out, unmarshalError(err)
}
func (c Client) GetOrganization(in *GetOrganizationIn) (*GetOrganizationOut, error) {
	if in == nil {
		in = new(GetOrganizationIn)
	}
	out := new(GetOrganizationOut)
	err := c.Client.Do("com.redhat.rhc.testing.rhsm.consumer.GetOrganization", in, out)
	return out, unmarshalError(err)
}
func (c Client) GetUUID(in *GetUUIDIn) (*GetUUIDOut, error) {
	if in == nil {
		in = new(GetUUIDIn)
	}
	out := new(GetUUIDOut)
	err := c.Client.Do("com.redhat.rhc.testing.rhsm.consumer.GetUUID", in, out)
	return out, unmarshalError(err)
}

type Backend interface {
	GetEnvironments(*GetEnvironmentsIn) (*GetEnvironmentsOut, error)
	GetOrganization(*GetOrganizationIn) (*GetOrganizationOut, error)
	GetUUID(*GetUUIDIn) (*GetUUIDOut, error)
}

type Handler struct {
	Backend Backend
}

func marshalError(err error) error {
	var name string
	switch err.(type) {
	case *SystemNotRegisteredError:
		name = "com.redhat.rhc.testing.rhsm.consumer.SystemNotRegistered"
	default:
		return err
	}
	return &govarlink.ServerError{
		Name:       name,
		Parameters: err,
	}
}
func (h Handler) HandleVarlink(call *govarlink.ServerCall, req *govarlink.ServerRequest) error {
	var (
		out interface{}
		err error
	)
	switch req.Method {
	case "com.redhat.rhc.testing.rhsm.consumer.GetEnvironments":
		in := new(GetEnvironmentsIn)
		if err := json.Unmarshal(req.Parameters, in); err != nil {
			return err
		}
		out, err = h.Backend.GetEnvironments(in)
	case "com.redhat.rhc.testing.rhsm.consumer.GetOrganization":
		in := new(GetOrganizationIn)
		if err := json.Unmarshal(req.Parameters, in); err != nil {
			return err
		}
		out, err = h.Backend.GetOrganization(in)
	case "com.redhat.rhc.testing.rhsm.consumer.GetUUID":
		in := new(GetUUIDIn)
		if err := json.Unmarshal(req.Parameters, in); err != nil {
			return err
		}
		out, err = h.Backend.GetUUID(in)
	default:
		err = &govarlink.ServerError{
			Name:       "org.varlink.service.MethodNotFound",
			Parameters: map[string]string{"method": req.Method},
		}
	}
	if err != nil {
		return marshalError(err)
	}
	return call.CloseWithReply(out)
}

func (h Handler) Register(reg *govarlink.Registry) {
	reg.Add(&govarlink.RegistryInterface{
		Definition: "# Consumer interface for the RHSM API\n# Any method in this interface can be used only when the system is registered\ninterface com.redhat.rhc.testing.rhsm.consumer\n\n# Error returned when a method is called on an unregistered system\nerror SystemNotRegistered()\n\ntype EnvironmentOwner (\n    id: string,\n    key: ?string,\n    displayName: ?string,\n    href: ?string,\n    contentAccessMode: ?string\n)\n\ntype EnvironmentContent (\n    contentId: string,\n    enabled: bool\n)\n\ntype Environment (\n    id: string,\n    created: ?string,\n    updated: ?string,\n    name: ?string,\n    type: ?string,\n    description: ?string,\n    contentPrefix: ?string,\n    owner: ?EnvironmentOwner,\n    environmentContent: ?[]EnvironmentContent\n)\n\ntype Organization (\n    id: string,\n    key: string,\n    displayName: ?string,\n    created: ?string,\n    updated: ?string,\n    contentPrefix: ?string,\n    defaultServiceLevel: ?string,\n    logLevel: ?string,\n    contentAccessMode: ?string,\n    contentAccessModeList: ?string,\n    autobindHypervisorDisabled: ?bool,\n    autobindDisabled: ?bool,\n    lastRefreshed: ?string\n)\n\n# Return UUID from installed consumer certificate\nmethod GetUUID() -> (\n    uuid: string\n)\n\n# Return organization that the registered system belongs to.\n# The object mirrors Candlepin owner fields (e.g. key, displayName, id).\nmethod GetOrganization() -> (\n    org: Organization\n)\n\n# Return environments assigned to the registered consumer.\n# Returns an empty list when no environments are assigned.\nmethod GetEnvironments() -> (\n    environments: []Environment\n)\n",
		Name:       "com.redhat.rhc.testing.rhsm.consumer",
	}, h)
}
