name: Go

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: Updating ...
        run: sudo apt-get -qq update

      - uses: actions/checkout@v7

      - name: Setup go
        uses: actions/setup-go@v7
        with:
          go-version: "stable"

      - name: Go build (source)
        run: go build ./...

      - name: Go build (tests)
        run: go test ./...

      - name: Go vet
        run: go vet ./...
